import { Creator } from "@/types/creator";

export const mockCreators: Creator[] = [
  {
    id: "CR001",
    name: "Sarah Johnson",
    profilePhoto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    platform: ["Instagram", "TikTok"],
    followers: 1250000,
    avgEngagement: 4.8,
    industry: ["Fashion", "Lifestyle"],
    brandsCollaborated: ["Nike", "Adidas", "H&M", "Zara"],
    lastViewedOn: "2024-01-15",
    country: "USA",
    language: ["English", "Spanish"],
    views: 5000000,
    engagementsPerPost: 60000,
    relevanceFactor: 9.5,
    totalPosts: 450,
    platformStats: [
      { platform: "Instagram", followers: 850000, engagement: 5.2, posts: 320 },
      { platform: "TikTok", followers: 400000, engagement: 4.1, posts: 130 },
    ],
    posts: Array.from({ length: 10 }, (_, i) => ({
      id: `post-${i}`,
      type: i % 2 === 0 ? "video" : "image",
      thumbnail: `https://picsum.photos/seed/${i}/400/300`,
      platform: i % 2 === 0 ? "Instagram" : "TikTok",
      userName: "Sarah Johnson",
      followers: 1250000,
      likes: Math.floor(Math.random() * 100000) + 10000,
      comments: Math.floor(Math.random() * 5000) + 500,
      createdAt: new Date(Date.now() - i * 86400000).toISOString(),
    })),
  },
  {
    id: "CR002",
    name: "Alex Chen",
    profilePhoto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    platform: ["YouTube", "Instagram"],
    followers: 2800000,
    avgEngagement: 6.2,
    industry: ["Tech", "Gaming"],
    brandsCollaborated: ["Apple", "Samsung", "Razer", "Logitech"],
    lastViewedOn: "2024-01-20",
    country: "Canada",
    language: ["English", "Mandarin"],
    views: 15000000,
    engagementsPerPost: 174000,
    relevanceFactor: 9.8,
    totalPosts: 280,
    platformStats: [
      { platform: "YouTube", followers: 2100000, engagement: 7.1, posts: 180 },
      { platform: "Instagram", followers: 700000, engagement: 4.8, posts: 100 },
    ],
    posts: Array.from({ length: 10 }, (_, i) => ({
      id: `post-${i}`,
      type: "video",
      thumbnail: `https://picsum.photos/seed/tech${i}/400/300`,
      platform: "YouTube",
      userName: "Alex Chen",
      followers: 2800000,
      likes: Math.floor(Math.random() * 200000) + 50000,
      comments: Math.floor(Math.random() * 10000) + 1000,
      createdAt: new Date(Date.now() - i * 86400000).toISOString(),
    })),
  },
  {
    id: "CR003",
    name: "Emma Rodriguez",
    profilePhoto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    platform: ["Instagram", "YouTube"],
    followers: 890000,
    avgEngagement: 5.5,
    industry: ["Beauty", "Fashion"],
    brandsCollaborated: ["Sephora", "MAC", "Dior", "Chanel"],
    lastViewedOn: "2024-01-18",
    country: "UK",
    language: ["English", "French"],
    views: 3500000,
    engagementsPerPost: 48950,
    relevanceFactor: 8.7,
    totalPosts: 520,
    platformStats: [
      { platform: "Instagram", followers: 650000, engagement: 5.8, posts: 380 },
      { platform: "YouTube", followers: 240000, engagement: 4.9, posts: 140 },
    ],
    posts: Array.from({ length: 10 }, (_, i) => ({
      id: `post-${i}`,
      type: i % 3 === 0 ? "video" : "image",
      thumbnail: `https://picsum.photos/seed/beauty${i}/400/300`,
      platform: i % 3 === 0 ? "YouTube" : "Instagram",
      userName: "Emma Rodriguez",
      followers: 890000,
      likes: Math.floor(Math.random() * 80000) + 20000,
      comments: Math.floor(Math.random() * 4000) + 800,
      createdAt: new Date(Date.now() - i * 86400000).toISOString(),
    })),
  },
  {
    id: "CR004",
    name: "Marcus Thompson",
    profilePhoto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus",
    platform: ["TikTok", "Instagram"],
    followers: 3200000,
    avgEngagement: 7.3,
    industry: ["Fitness", "Lifestyle"],
    brandsCollaborated: ["Nike", "Under Armour", "Gatorade", "Protein World"],
    lastViewedOn: "2024-01-22",
    country: "USA",
    language: ["English"],
    views: 20000000,
    engagementsPerPost: 233600,
    relevanceFactor: 9.2,
    totalPosts: 680,
    platformStats: [
      { platform: "TikTok", followers: 2400000, engagement: 8.1, posts: 480 },
      { platform: "Instagram", followers: 800000, engagement: 5.8, posts: 200 },
    ],
    posts: Array.from({ length: 10 }, (_, i) => ({
      id: `post-${i}`,
      type: "video",
      thumbnail: `https://picsum.photos/seed/fitness${i}/400/300`,
      platform: "TikTok",
      userName: "Marcus Thompson",
      followers: 3200000,
      likes: Math.floor(Math.random() * 300000) + 100000,
      comments: Math.floor(Math.random() * 15000) + 5000,
      createdAt: new Date(Date.now() - i * 86400000).toISOString(),
    })),
  },
  {
    id: "CR005",
    name: "Priya Sharma",
    profilePhoto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    platform: ["Instagram", "YouTube"],
    followers: 1500000,
    avgEngagement: 5.9,
    industry: ["Food", "Travel"],
    brandsCollaborated: ["Airbnb", "Marriott", "KitchenAid", "HelloFresh"],
    lastViewedOn: "2024-01-19",
    country: "India",
    language: ["English", "Hindi"],
    views: 8000000,
    engagementsPerPost: 88500,
    relevanceFactor: 8.9,
    totalPosts: 420,
    platformStats: [
      { platform: "Instagram", followers: 1000000, engagement: 6.2, posts: 300 },
      { platform: "YouTube", followers: 500000, engagement: 5.3, posts: 120 },
    ],
    posts: Array.from({ length: 10 }, (_, i) => ({
      id: `post-${i}`,
      type: i % 2 === 0 ? "video" : "image",
      thumbnail: `https://picsum.photos/seed/food${i}/400/300`,
      platform: i % 2 === 0 ? "YouTube" : "Instagram",
      userName: "Priya Sharma",
      followers: 1500000,
      likes: Math.floor(Math.random() * 120000) + 40000,
      comments: Math.floor(Math.random() * 6000) + 1500,
      createdAt: new Date(Date.now() - i * 86400000).toISOString(),
    })),
  },
];

// Generate 50 more creators for pagination testing
for (let i = 6; i <= 55; i++) {
  const platforms = [["Instagram", "TikTok"], ["YouTube", "Instagram"], ["TikTok"], ["YouTube"]];
  const industries = [["Fashion", "Lifestyle"], ["Tech", "Gaming"], ["Beauty"], ["Fitness"], ["Food", "Travel"]];
  const countries = ["USA", "UK", "Canada", "India", "Australia", "Germany"];
  const languages = [["English"], ["English", "Spanish"], ["English", "French"], ["English", "Hindi"]];
  
  const randomPlatform = platforms[Math.floor(Math.random() * platforms.length)];
  const randomIndustry = industries[Math.floor(Math.random() * industries.length)];
  const followers = Math.floor(Math.random() * 5000000) + 100000;
  
  mockCreators.push({
    id: `CR${String(i).padStart(3, "0")}`,
    name: `Creator ${i}`,
    profilePhoto: `https://api.dicebear.com/7.x/avataaars/svg?seed=Creator${i}`,
    platform: randomPlatform,
    followers,
    avgEngagement: Math.random() * 8 + 2,
    industry: randomIndustry,
    brandsCollaborated: ["Nike", "Apple", "Samsung"].slice(0, Math.floor(Math.random() * 3) + 1),
    lastViewedOn: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString().split("T")[0],
    country: countries[Math.floor(Math.random() * countries.length)],
    language: languages[Math.floor(Math.random() * languages.length)],
    views: Math.floor(Math.random() * 20000000) + 500000,
    engagementsPerPost: Math.floor(Math.random() * 100000) + 10000,
    relevanceFactor: Math.random() * 5 + 5,
    totalPosts: Math.floor(Math.random() * 500) + 100,
    platformStats: randomPlatform.map(p => ({
      platform: p,
      followers: Math.floor(followers / randomPlatform.length),
      engagement: Math.random() * 8 + 2,
      posts: Math.floor(Math.random() * 300) + 50,
    })),
    posts: Array.from({ length: 10 }, (_, j) => ({
      id: `post-${i}-${j}`,
      type: j % 2 === 0 ? "video" : "image",
      thumbnail: `https://picsum.photos/seed/${i}${j}/400/300`,
      platform: randomPlatform[0],
      userName: `Creator ${i}`,
      followers,
      likes: Math.floor(Math.random() * 100000) + 10000,
      comments: Math.floor(Math.random() * 5000) + 500,
      createdAt: new Date(Date.now() - j * 86400000).toISOString(),
    })),
  });
}
